services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    hostname: frontend
    volumes:
      - ./frontend:/opt/frontend/
    ports:
      - 5173:5173
    restart: always
  api:
    build:
      context: ./api
      dockerfile: dev.Dockerfile
    hostname: api
    volumes:
      - ./api:/opt/api
    ports:
      - 8000:8000
    restart: always
  mongo:
    image: mongo:6.0.7
    environment:
      - MONGO_INITDB_ROOT_USERNAME=bill-split
      - MONGO_INITDB_ROOT_PASSWORD=bill-split
      - MONGO_INITDB_DATABASE=bill-split
    volumes:
      - mongo-data:/data/db